### ISSUE TITLE
error: a type with the same simple import com.wheelpicker.WheelPickerPackage;

### ISSUE THREAD

**Issue by vivkikkk** [ElekenAgency/ReactNativeWheelPicker#138]
error: a type with the same simple name is already defined by the single-type-import of WheelPickerPackage
import com.wheelpicker.WheelPickerPackage;
![Screen Shot 2563-10-14 at 13 19 43](https://user-images.githubusercontent.com/40588602/95951203-3e2fe280-0e20-11eb-9262-526fa3a8bf1f.png)

**Comment by lethienhung** [comment]
I've the same issue. Did you resolve this @methineeinkan? How can I change the import package as different name?
