### ISSUE TITLE
Strictly Android?

### ISSUE THREAD

**Issue by kiorq** [ElekenAgency/ReactNativeWheelPicker#15]
Is this strictly android? can this work with iOS as well? Trying to find an all in one solution

**Comment by raduflp** [comment]
as far as I can tell yes, it's Android only. 
you have the native PickerIOS though and it's just a matter of creating a custom component that will take into consideration the platform.

Shouldn't be difficult to create an platform agnostic abstraction over the current api, but really depends on the owner's vision of the package. 

I might do a PR in the future if people are interested
