### ISSUE TITLE
Wheel Picker not being rendered on CRNA using Expo

### ISSUE THREAD

**Issue by sidd607** [ElekenAgency/ReactNativeWheelPicker#16]
Wheel Picker not being rendered on CRNA using Expo
I tried the example, It keeps giving the warning
`
Native component for "WheelPicker" does not exist
`
and nothing renders.

**Comment by mikaello** [comment]
`react-native-wheel-picker-android` contains native Android code, and to make it work, you need to run `react-native link react-native-wheel-picker-android`, which may not be compatible with CRNA using Expo. See this SO-answer for more information about adding libraries with native code: https://stackoverflow.com/questions/41597414/can-you-add-libraries-with-native-dependencies-to-an-expo-react-native-project
