### ISSUE TITLE
TimePicker only shows up as three red boxes

### ISSUE THREAD

**Issue by johngoren** [ElekenAgency/ReactNativeWheelPicker#20]
Thanks for this module. When I try the TimePicker or the DatePicker, on my RN 0.47.2 Android app it shows up as three red boxes with no wheels, though.

<img width="233" alt="screenshot 2017-08-30 12 20 07" src="https://user-images.githubusercontent.com/748214/29870090-c2b3f4d2-8d7d-11e7-8c6e-3fe4460ba239.png">

**Comment by jigaryadav** [comment]
getting the same red box in IOS but working in android 

  

"react": "16.0.0-alpha.6"
"react-native": "^0.44.0"
"react-native-wheel-picker-android": "^0.1.10"

![screen shot 2017-09-27 at 4 42 51 pm](https://user-images.githubusercontent.com/22216148/30910600-fe8477ee-a3a2-11e7-9fec-51278c80fad4.png)

**Comment by ArtemKosiakevych** [comment]
@johngoren Red boxes means that Native UI Component can't bridge to RN, just type in your terminal `react-native link react-native-wheel-picker-android`

**Comment by ArtemKosiakevych** [comment]
@jigaryadav
This library only for android platform.
For IOS platform you can use `PickerIOS` that looks like wheel picker in this library.

**Comment by Ravikumarsd** [comment]
i need to display the picked date in Text Component ..please help me
