### ISSUE TITLE
Add MomentJS as a dependency 

### ISSUE THREAD

**Issue by raduflp** [ElekenAgency/ReactNativeWheelPicker#21]
'moment' is used in TimePicker and DatePicker but not included as a dependency in package.json

**Comment by grootendorste** [comment]
Hi, yes, I can't run it without it. It seems to be there.

**Comment by raduflp** [comment]
I have opened the issue because in the package.json of ReactNativeWheelPicker moment is not included included in the dependencies section, so it is not automatically added on npm install, which imho it should.

**Comment by ArtemKosiakevych** [comment]
@raduflp Check please `package.json` again
