### ISSUE TITLE
Scrolling and stopping wheel does not pick value

### ISSUE THREAD

**Issue by mikaello** [ElekenAgency/ReactNativeWheelPicker#29]
**Reproduce:**

1.  Create a app with `WheelPicker` component and set the  `isCyclic` prop to true (or create a large list of values)
2. Run the app
3. Swipe fast up or down on the wheel picker so the wheel starts spinning
4. Stop the wheel by touching it once
5. The value that was selected is not sent back in the callback `onItemSelected`

If you let the wheel stop by itself or you scroll slowly the value is sent in the callback `onItemSelected` as expected.

![bug](https://user-images.githubusercontent.com/2505178/31823755-6a69978e-b5ad-11e7-81d2-40237a4aac5f.png)

**Comment by mikaello** [comment]
After some research in the issue tracker for AigeStudio/WheelPicker it seems to be a bug related to that module, and nothing that is the responsibility of this wrapper-module. E.g. [issue #71](https://github.com/AigeStudio/WheelPicker/issues/71) seem to be related.

The last comment in that issue indicates that this is may be resolved in master branch of AigeStudio/WheelPicker.

**Comment by omerman** [comment]
@mikaello
I tried to install your changes, it seemed to resolve the issue,
but it might break the bridge since on the first load supplying `selectedItemPosition` is ignored :<
did you happen to come across this?

**Comment by mikaello** [comment]
I haven't used this module lately, so that bug was unbeknown to me. If you will you could send a PR to my branch and it could then complement this PR.
