### ISSUE TITLE
onItemSelected callback won't change my state

### ISSUE THREAD

**Issue by ionwyn** [ElekenAgency/ReactNativeWheelPicker#34]
I have an implementation as follow:

```
<WheelPicker onItemSelected={ (event)=> this.setState({ minute: event.data }) } />
```

This gives me an error 'undefined is not a function'.

Any fix?  I am new React Native so I may be missing my basics, any help is appreciated!

**Comment by Beginner888** [comment]
The props in the event is {position, data}, so the correct syntax is : 
`<WheelPicker onItemSelected={ (event)=> this.setState({ index: event.position, minute: event.data }) } />`

index type is Number
