### ISSUE TITLE
Disable time wheel in DateTime wheel picker

### ISSUE THREAD

**Issue by Shhzdmrz** [ElekenAgency/ReactNativeWheelPicker#42]
Hello,
Is there any way to disable the wheel for past time selection? For my case I want to allow user to select current or future time for the current day or next day but to avoid him to select previous time by disabling the time picker for previous time like we are doing for the day which is started from today only. Can we do this type of functionality or is there any workaround?

Thanks

**Comment by ArtemKosiakevych** [comment]
If you need to disable past time do it manually if user pick a time in past set `selectedItemPosition` to a current time programmatically
