### ISSUE TITLE
Blank with red border around component

### ISSUE THREAD

**Issue by StephenTANM** [ElekenAgency/ReactNativeWheelPicker#43]
I get this blank square with a red border around the component instead of the picker. I did the npm install and linked it multiple times and still no dice. Am I supposed to install the component from the link you have provided first?

**Comment by HotSpotNick** [comment]
Me to, Any dice?

**Comment by HotSpotNick** [comment]
@StephenTANM  Did you find a solution??

**Comment by ArtemKosiakevych** [comment]
Do link manually and make sure you're using Picker for android platform
