### ISSUE TITLE
DatePicker only set to increment minutes by 5.

### ISSUE THREAD

**Issue by t-hughes** [ElekenAgency/ReactNativeWheelPicker#44]
The DatePicker wheel still increments by 5 even if you pass a minutes array that goes from '00' - '59'. I am using version 1.0.3. The issue reported in #19 still occurs on the DatePicker wheel. The example provided in issue #19 only gave the TimePicker example so therefore the issue was only fixed for TimePicker. Would it be possible to get the same 3 line code fix that was introduced to fix TimePicker introduced in DatePicker?

**Comment by ArtemKosiakevych** [comment]
Sure, thank you for an issue. Resolved
