### ISSUE TITLE
Different runtime errors when using different pickers

### ISSUE THREAD

**Issue by MiLeung** [ElekenAgency/ReactNativeWheelPicker#47]
When I try to use DatePicker, I get the following error:
Invariant Violation: View config not found for name WheelPicker

When I try to use WheelPicker, I get the following error:
Invariant Violation: Native component for "WheelPicker" does not exist

I have already linked react-native-wheel-picker-android (shouldn't this be in the docs?)

**Comment by nojas01** [comment]
same here, using wheelPicker gives the following error:

Invariant Violation: View config not found for name WheelPicker
This error is located at:
    in WheelPicker (at WheelPicker.js:61)
....

**Comment by Tracklous** [comment]
@nojas01  @MiLeung Maybe **reinstalling** the apk will work you guys.

>  I mean after adding and linking the package just reinstall your app.
