### ISSUE TITLE
Native component for "WheelPicker" does not exist

### ISSUE THREAD

**Issue by axelkennedal** [ElekenAgency/ReactNativeWheelPicker#52]
I tried to add this component to my app, but when I do so I get:

```
Invariant Violation: Native component for "WheelPicker" does not exist

This error is located at:
  in WheelPicker (at WheelPicker.js:61)
  ...(more stacktrace output)
```

What I've done:

1. `yarn add react-native-wheel-picker-android`
1.  added it to my app like so:
```
import { WheelPicker } from "react-native-wheel-picker-android";

...
return (
<View>
  <WheelPicker
    data={[1,2,3,4,5]}
    style={{width: 100, height: 100}}
  />
</View>
);
``` 

3. Run `react-native run-android`

**Comment by mohammed-adil-moughal** [comment]
Same ISSUE here

**Comment by ImHamzaAnwer** [comment]
Same Issue

**Comment by welladam** [comment]
Same here

**Comment by danaee123** [comment]
Same here

**Comment by ArtemKosiakevych** [comment]
Thx for issue, just do `react-native link react-native-wheel-picker-android`

**Comment by drunkel** [comment]
Would like to see this re-opened. Have linked and verified that the link _looks_ correct, but still getting this error.

**Comment by SiddharthChoudhary** [comment]
Yeah! Please reopen it, I am still getting the same error, though I have already tried linking the react-native link

**Comment by mosesmc52** [comment]
Same here

**Comment by Kseg97** [comment]
This is still a problem for those who use Expo and don't want to use link

**Comment by fjobeir** [comment]
Automatic link did all steps mentioned by @mosesmc52  except these related to MainApplication.java 

Thanks @mosesmc52
