### ISSUE TITLE
Does not work when select any item programatically on Android

### ISSUE THREAD

**Issue by hdongre-techracers** [ElekenAgency/ReactNativeWheelPicker#62]
I have list to show on picker and I want to select lets say third item programatically. So it should show third item default as selected when I open the picker. But it is not happening right now.

**Comment by ArtemKosiakevych** [comment]
You can set selected item programmatically, for this use `selectedItemPosition`

**Comment by seanyusa** [comment]
@ArtemKosiakevych I don't think this works on Android. I'm assuming because the WheelPicker android library does not support this?
