### ISSUE TITLE
App not build

### ISSUE THREAD

**Issue by janaka120** [ElekenAgency/ReactNativeWheelPicker#67]
When I tried to build an Apk. ReactNativeWheelPicker Lib gives this error message.

`error: resource android:style/TextAppearance.Material.Widget.Button.Colored not found.`

I try to resolve it. But I couldn't find out a solution.
Thank you.

**Comment by jojjesv** [comment]
Try setting something like `targetSdkVersion 27` in your `app/build.gradle`.
