### ISSUE TITLE
Crash the app in react-native 0.57

### ISSUE THREAD

**Issue by suihalee** [ElekenAgency/ReactNativeWheelPicker#73]
Crash the app in react-native 0.57, could you help to check?

**Comment by geordidearns** [comment]
@ArtemKosiakevych Still receiving this error on react native 59.0

Steps i took:

- Add package via yarn
- link the package
- use stripped down WheelPicker passing only an array of numbers into the data prop

run on android emulator and it crashes with 'java.lang.ArithmeticException: divide by zero' (com.wheelpicker.LoopView.onDraw(LoopView.java:195))

Thanks

**Comment by sobanfly** [comment]
I fixed it by marking array of strings.

**Comment by sobanfly** [comment]
also if you are dynamically creating data set, please check 
`array && array.length >=1 `
secondly converts data into string
