### ISSUE TITLE
hide indicator

### ISSUE THREAD

**Issue by mun5865** [ElekenAgency/ReactNativeWheelPicker#74]
Hi, I'm new to react native. In my case, I would like to hide the line in the wheelpicker, should I use the `hideIndicator` function? What should I suppose to do in the function? Did I have to set something to `false` ? Can someone give me some example or guide?

**Comment by ArtemKosiakevych** [comment]
@mun5865 `<WheelPicker hideIndicator/>` that's all

**Comment by 6axter82** [comment]
Not working at all

**Comment by whenmoon** [comment]
This doesn't work :(
