### ISSUE TITLE
Does not accept colors in rgba format

### ISSUE THREAD

**Issue by sbycrosz** [ElekenAgency/ReactNativeWheelPicker#77]
Awesome work on the library!

I found the library throws an error when given colors in rgba format (e.g. rgba(255, 0, 170, 0.8))

![screenshot 2019-01-24 at 12 20 21 pm](https://user-images.githubusercontent.com/4867178/51654348-77804900-1fd2-11e9-8666-d8cc2bc1b878.png)

Cheers!

**Comment by ArtemKosiakevych** [comment]
@sbycrosz Thanks for the issue, fixed in 2.0.5 version!
