### ISSUE TITLE
Changing wheelpicker value dinamically

### ISSUE THREAD

**Issue by antakov** [ElekenAgency/ReactNativeWheelPicker#9]
Is there a possibility to change a value of wheel dinamically? For example, there are two wheelpickers and they are depended one from another. I want to change a value of the first one when the value of second one changes. Changing of selectedItemPosition value doesnt calls rerender of the wheelpicker. Thank you.

**Comment by ArtemKosiakevych** [comment]
@antakov Thank you for issue, this bug was fixed in 1.0.3 version
